name: Feature Request
description: Request a new feature or changes
title: '[Feature Request]: '
body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        e.g. current problems, use cases, ...
  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: Issues disregarding this section will be closed.
      options:
        - label: >-
            I have searched the existing issues and this is NOT a duplicate of
            an already open or closed issue.
          required: true
        - label: >-
            I am aware that I'm requesting a feature for the iOS version.
          required: true
